name: 04-Using Actions
run-name: ${{github.actor}} is deploying
on: [push]
jobs:
    Build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4
            # - name: Printing Folder  
            #   run: tree
            - name: Setup node
              run:
                |
                 cd 04-using-actions/my-react-app
                 npm ci
            # - name: Run unit Tests
            #   run: 
            #     |
            #      cd 04-using-actions/my-react-app
            #      npm run test

                 

                  