name: 04-Using Actions
run-name: ${{github.actor}} is deploying
on: [push]
jobs:
    Build:
        runs-on: ubuntu-latest
        defaults:
          run: 
               working-directory: 04-using-actions/my-react-app
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4
            # - name: Printing Folder  
            #   run: tree
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: "20.x"
            - name: Install Dependancies
              # run:
              #   |    
              #    cd 04-using-actions/my-react-app
              #    npm ci
              # or
              # working-directory: 04-using-actions/my-react-app
              run: npm ci
            - name: Run unit Tests
              run: 
                |
                 cd 04-using-actions/my-react-app
                 npm run test
              # or
              # working-directory: 04-using-actions/my-react-app #(do not repeat anything on code so use default and run  "working-directory: 04-using-actions/my-react-app")in line no 7

                 

                  