name: BuildingBlocks
run-name: ${{github.actor}} is deploying
on: [push,workflow_dispatch]
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps: 
            - name: echo-hello
              run: ech "Hello World"          
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: echo-fail
              run: |
                  echo "I will fail"
                  exit 0 
            - name: echo-bye      
              run: echo "Good bye" 
