name: eventfilters_activitytype
on: 
    pull_request:
        types: [opened,synchronize]
        branches: 
             - main            
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever PR is opened Or synchronised and based branch is main" 
