name: Firstworkflow
run-name: ${{github.actor}} is deploying
on: [push]
jobs:
    shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: echo "Hello World"
            - name: Multiline commands
              run: |
                node -v
                npm -v
             
