name: workflow-run
on: 
    workflow_run:
        workflows: [Firstworkflow]
        types:
            - completed
jobs:
    Hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I am running beacuse the repo events........"            

